In [1]:
import pandas as pd
import numpy as np

### Load the Data

In [2]:
preprocessed_data = pd.read_csv('df_preprocessed_alt.csv')
absenteeism_data = preprocessed_data.copy()
absenteeism_data.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

Since we are dealing with a logistic regression, we need to classify our targets into two classes and assign them values of 0 and 1. Here we will create two classes - Moderately absent and Excessively absent representing values zero and 1

### Create the targets

In [3]:
# To classify our targets, we obtain the median value of the Absenteeism Time in Hours and then use it to create our
# two classes

np.median(absenteeism_data['Absenteeism Time in Hours'])

3.0

In [4]:
# We create a targets variable to hold the classified targets
targets = np.where(absenteeism_data['Absenteeism Time in Hours'] <= 
                   np.median(absenteeism_data['Absenteeism Time in Hours']), 0, 1)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [5]:
absenteeism_data['Excessive Absenteeism'] = targets
absenteeism_data

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0                 30          0         2     1                          4   
1                 31          0         1     0                          0   
2                 31          0         0     0                          2   
3                 24          0         2     0                          4   
4                 30          0         2     1                          2   
..               ...        ...       ...   ...                        ...   
695               22          1         2     0                          8   
696               24          0         1     2                          3   
697               25          1         0     0                          8   
698               25          1         0     0                          2   
699               25          0         1     1                          2   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 16 columns]

In [6]:
# Using the median for mapping our targets has also helped us accomplish another goal implicitly - Balancing the 
# dataset. This allows our priors to be balances such that we do not train or fit our model on unbalanced priors.
# To validate this, we take the sum of the targets and divide by the total number of targets

priors = targets.sum()/targets.shape[0]
priors

0.45571428571428574

In [7]:
# We drop the Absenteeism in Hours column as it is no longer needed

data_with_targets = absenteeism_data.drop(['Absenteeism Time in Hours'], axis = 1)

In [8]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0               30          0         2     1                      1  
1               31          0         1     0                      0  
2               31          0         0     0                      0  
3               24          0         2     0                      1  
4               30          0         2     1                      0

In [9]:
# We specify our input variables
unscaled_inputs = data_with_targets.iloc[:,:-1]

### Scaling the inputs

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
scaler = StandardScaler() # We create a scaler object here in order to scale some parts of the inputs as we do not
# want to scale the dummies

scaler.fit(unscaled_inputs[['Month Value','Day of the Week', 'Transportation Expense', 'Distance to Work',
                           'Age', 'Daily Work Load Average', 'Body Mass Index', 'Children','Pets']])

StandardScaler(copy=True, with_mean=True, with_std=True)

In [12]:
unscaled_inputs[['Month Value','Day of the Week', 'Transportation Expense', 'Distance to Work',
                           'Age', 'Daily Work Load Average', 'Body Mass Index', 'Children','Pets']] = scaler.transform(
unscaled_inputs[['Month Value','Day of the Week', 'Transportation Expense', 'Distance to Work',
                           'Age', 'Daily Work Load Average', 'Body Mass Index', 'Children','Pets']])

In [13]:
scaled_inputs = np.array(unscaled_inputs)

In [14]:
scaled_inputs

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.88046927,  0.26848661],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
        -0.01928035, -0.58968976],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
        -0.91902997, -0.58968976],
       ...,
       [ 1.        ,  0.        ,  0.        , ...,  1.        ,
        -0.91902997, -0.58968976],
       [ 0.        ,  0.        ,  0.        , ...,  1.        ,
        -0.91902997, -0.58968976],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
        -0.01928035,  0.26848661]])

In [15]:
scaled_inputs.shape

(700, 14)

### Define the target

In [16]:
targets = data_with_targets.iloc[:,-1]

In [17]:
targets

0      1
1      0
2      0
3      1
4      0
      ..
695    1
696    0
697    1
698    0
699    0
Name: Excessive Absenteeism, Length: 700, dtype: int64

### Shuffle the dataset and split

In [18]:
# shuffled_indices = np.arange(scaled_inputs.shape[0])
# np.random.shuffle(shuffled_indices)

# shuffled_inputs = scaled_inputs[shuffled_indices]
# shuffled_targets = targets[shuffled_indices]

In [19]:
# shuffled_inputs.shape

In [20]:
# shuffled_targets.shape

In [21]:
# Split the dataset into training and testing data. We use an 80-20 split for the dataset. The shuffle
# parameter is set to true by default to shuffle the dataset before splitting. To also ensure this dataset 
# is not shuffled everytime we re-run the code. We use a random state of 365

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets,
                                                    test_size = 0.2, random_state=365)

In [22]:
x_train.shape, x_test.shape

((560, 14), (140, 14))

In [23]:
y_train.shape, y_test.shape

((560,), (140,))

### Model Training

In [24]:
# import statsmodels.api as sm

In [25]:
# x = sm.add_constant(x_train)
# log_result = sm.Logit(y_train,x).fit()

In [26]:
# log_result.summary()

In [27]:
# From the output above, we see that statsmodels runs out of iterations during model training. Hence we need to use 
# another library to train the model

from sklearn.linear_model import LogisticRegression

In [28]:
log_model = LogisticRegression()
log_model.fit(x_train,y_train)

/usr/local/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [29]:
# To check the performance of the model i.e how well our model learn how to classify inputs based on the training data
# we use the score(R-squared)

log_model.score(x_train,y_train)

0.7660714285714286

In [30]:
# From the score, we see that our model learns how to classify up to 76% of the data accurately, now let us check that
# manually to verify

### Checking the Model accuracy

In [31]:
# We bascially compare the outputs with the targets. The outputs are predictions of the training inputs
model_output = log_model.predict(x_train)
model_output

array([1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,

In [32]:
np.array(y_train)

array([1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [33]:
model_output == np.array(y_train)

array([ True,  True, False,  True,  True,  True, False,  True, False,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True, False,  True,  True,  True,  True, False,
       False, False,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True, False,
        True,  True,  True,  True, False,  True,  True, False, False,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True, False, False, False,  True, False,
       False, False,  True,  True, False,  True,  True,  True,  True,
        True,  True,

In [34]:
# Since these boolean values are represented as 0s and 1s, we run a sum over the comparison and divide by the number
# of observations

model_accuracy = np.sum(model_output == np.array(y_train))/x_train.shape[0]
model_accuracy

0.7660714285714286

In [35]:
# Fetch the coefficients and intercept
log_model.coef_

array([[ 2.50593457,  1.2284419 ,  2.76540445,  0.71043106,  0.14490752,
        -0.14373434,  0.51901649, -0.04528689, -0.2550559 , -0.02334453,
         0.31771413, -0.12275229,  0.44743598, -0.31640777]])

In [36]:
log_model.intercept_

array([-1.38919769])

### Create a Summary Table

In [37]:
# We create a summary table to hold the features and their coefficients, as well as the intercept. 
#Since sklearn makes use of arrays, we will have to transform our data into dataframes

features = unscaled_inputs.columns.values
summary_table = pd.DataFrame(columns=['Features'], data=features)
summary_table['coefficients'] = np.transpose(log_model.coef_) # By default, ndarrays are rows only so we transpose them
# summary_table['intercept'] = np.transpose(log_model.intercept_)

summary_table

Features  coefficients
0                  Reason_1      2.505935
1                  Reason_2      1.228442
2                  Reason_3      2.765404
3                  Reason_4      0.710431
4               Month Value      0.144908
5           Day of the Week     -0.143734
6    Transportation Expense      0.519016
7          Distance to Work     -0.045287
8                       Age     -0.255056
9   Daily Work Load Average     -0.023345
10          Body Mass Index      0.317714
11                Education     -0.122752
12                 Children      0.447436
13                     Pets     -0.316408

In [38]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', log_model.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Features  coefficients
0                 Intercept     -1.389198
1                  Reason_1      2.505935
2                  Reason_2      1.228442
3                  Reason_3      2.765404
4                  Reason_4      0.710431
5               Month Value      0.144908
6           Day of the Week     -0.143734
7    Transportation Expense      0.519016
8          Distance to Work     -0.045287
9                       Age     -0.255056
10  Daily Work Load Average     -0.023345
11          Body Mass Index      0.317714
12                Education     -0.122752
13                 Children      0.447436
14                     Pets     -0.316408

In [39]:
# Since logistic deals with the log(odds), we can calculate the odds ratio of the coefficients to determine which 
# coefficients have the highest weights

summary_table['odds_ratio'] = np.exp(summary_table.coefficients)
summary_table

Features  coefficients  odds_ratio
0                 Intercept     -1.389198    0.249275
1                  Reason_1      2.505935   12.255007
2                  Reason_2      1.228442    3.415903
3                  Reason_3      2.765404   15.885464
4                  Reason_4      0.710431    2.034868
5               Month Value      0.144908    1.155933
6           Day of the Week     -0.143734    0.866118
7    Transportation Expense      0.519016    1.680374
8          Distance to Work     -0.045287    0.955723
9                       Age     -0.255056    0.774873
10  Daily Work Load Average     -0.023345    0.976926
11          Body Mass Index      0.317714    1.373983
12                Education     -0.122752    0.884483
13                 Children      0.447436    1.564296
14                     Pets     -0.316408    0.728762

In [40]:
summary_table = summary_table.sort_values(['odds_ratio'], ascending=False)
summary_table

Features  coefficients  odds_ratio
3                  Reason_3      2.765404   15.885464
1                  Reason_1      2.505935   12.255007
2                  Reason_2      1.228442    3.415903
4                  Reason_4      0.710431    2.034868
7    Transportation Expense      0.519016    1.680374
13                 Children      0.447436    1.564296
11          Body Mass Index      0.317714    1.373983
5               Month Value      0.144908    1.155933
10  Daily Work Load Average     -0.023345    0.976926
8          Distance to Work     -0.045287    0.955723
12                Education     -0.122752    0.884483
6           Day of the Week     -0.143734    0.866118
9                       Age     -0.255056    0.774873
14                     Pets     -0.316408    0.728762
0                 Intercept     -1.389198    0.249275

### Interpreting the Summary table

We know that a feature is not particularly important when the coefficient is zero or the odds ratio is 1 i.e. for 
each unit increase in that feature, the odds will increase by a multiple of the odds ratio. Therefore, a ratio of 1
gives us no increase in the odds.

The features that have the most impact on excessive seem to be each of the reasons given with each group as follows:
1. Various Diseases
2. Pregnancy and childbirth
3. Poisoning
4. Light diseases

We see that an employee is 15 times more likely to be excessively absent when they are poisoned, which seems reasonable, and 12, 3 and 2 for reasons 1, 2 and 4 respectively

The transportation expense is next on the hierarchy as we see that for each unit increase in Transportation expense, the employee is more than 1.5 times likely to be excessively absent

The pets also informs us that for each(standardized) unit increase in the number of pets, an employee is less likely
to be absent. This could infer that with an increase in the number of pets, an employee could hire a caretaker rather than being absent from work OR employees with pets tend to be happier and are therefore less absent at work.

The Education tells us that for employees with a higher level of education, they are less likely to be excessively absent from work. 

In another notebook, we simplify this model by dropping the features with low weights(coefficients). These include the following
1. Month Value
2. Daily Work Load Average
3. Distance to work 

These are the features with weights most closest to zero. 

### Testing the Model

In [41]:
log_model.score(x_test,y_test)

0.7571428571428571

In [42]:
# We analyse the outputs of the test dataset using the predict_proba method in sklearn. This gives us the probability 
# of  the values being zero and 1

predicted_proba = log_model.predict_proba(x_test)

In [43]:
predicted_proba

array([[0.56516453, 0.43483547],
       [0.62405032, 0.37594968],
       [0.46939453, 0.53060547],
       [0.12741263, 0.87258737],
       [0.25801426, 0.74198574],
       [0.39989309, 0.60010691],
       [0.21824307, 0.78175693],
       [0.49277409, 0.50722591],
       [0.58907009, 0.41092991],
       [0.32679737, 0.67320263],
       [0.84752104, 0.15247896],
       [0.87556752, 0.12443248],
       [0.70533045, 0.29466955],
       [0.45068125, 0.54931875],
       [0.31269813, 0.68730187],
       [0.64360947, 0.35639053],
       [0.45109715, 0.54890285],
       [0.45432425, 0.54567575],
       [0.62845615, 0.37154385],
       [0.80443209, 0.19556791],
       [0.878312  , 0.121688  ],
       [0.67479196, 0.32520804],
       [0.35173371, 0.64826629],
       [0.46164677, 0.53835323],
       [0.81849485, 0.18150515],
       [0.46875698, 0.53124302],
       [0.83706245, 0.16293755],
       [0.76034418, 0.23965582],
       [0.32114244, 0.67885756],
       [0.65369246, 0.34630754],
       [0.

In [45]:
# Since we are interested in the 1s i.e. the employees that are excessively absent, we can pull the probabilities in the
# second column
predicted_proba[:,1]

array([0.43483547, 0.37594968, 0.53060547, 0.87258737, 0.74198574,
       0.60010691, 0.78175693, 0.50722591, 0.41092991, 0.67320263,
       0.15247896, 0.12443248, 0.29466955, 0.54931875, 0.68730187,
       0.35639053, 0.54890285, 0.54567575, 0.37154385, 0.19556791,
       0.121688  , 0.32520804, 0.64826629, 0.53835323, 0.18150515,
       0.53124302, 0.16293755, 0.23965582, 0.67885756, 0.34630754,
       0.75343445, 0.19736123, 0.59693534, 0.68293334, 0.36321863,
       0.74454236, 0.60903392, 0.53797882, 0.5816952 , 0.6597596 ,
       0.88420566, 0.71733499, 0.25422965, 0.27308659, 0.22220405,
       0.93193445, 0.54935566, 0.3980929 , 0.79532095, 0.2761744 ,
       0.22795294, 0.41350074, 0.86818815, 0.18512391, 0.51741065,
       0.68774941, 0.47535806, 0.24417624, 0.21009984, 0.39282978,
       0.31158361, 0.40355283, 0.63802591, 0.57182975, 0.39252328,
       0.57556788, 0.72753976, 0.23316471, 0.27154022, 0.27357829,
       0.70710009, 0.17846296, 0.10955638, 0.49722865, 0.32152